services:
  db:
    image: agnohq/pgvector:18
    environment:
      POSTGRES_DB: ai
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: ai
    ports:
      - "5532:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
